// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use environment variables if available, otherwise fallback to hardcoded values
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://pfrzcecnwgnxvpjhjoqr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBmcnpjZWNud2dueHZwamhqb3FyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3MTM5NzcsImV4cCI6MjA1NzI4OTk3N30.ebY5nc__KsaS6ncoDloXVnB-ZRAsqyn4e2qv-6_ysNk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create client with session persistence enabled
export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      storageKey: 'farmease-auth-token',
      autoRefreshToken: true,
      detectSessionInUrl: true,
    }
  }
);